import re
seq = "ATGCAATCGACTACGATCAATCGAGGGCC"
#count the number of fragments that can be generated by the EcoRI enzymes
fragments_number = re.findall(r"GAATTC",seq)
#one cut generates two fragments
print (int(len(fragments_number))+1)
#no "GAATTC" sequence so the DNA sequence is the same
